name: Deploy infra multicloud

on:
  push:
    branches:
      - main

jobs:
  deploy-aws:
    name: Deploy en AWS
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./AWS
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Init Terraform
        run: terraform init

      - name: Apply Terraform
        run: terraform apply -auto-approve

  deploy-azure:
    name: Deploy en Azure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./AZ 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Login Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Init Terraform
        run: terraform init

      - name: Apply Terraform
        run: terraform apply -auto-approve
