name: Terraform Destroy

on:
  workflow_dispatch:  # Permite ejecutar el workflow manualmente

jobs:
  destroy-aws:
    name: Destroy en AWS
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./AWS
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Init Terraform
        run: terraform init

      - name: Destroy recursos en AWS
        run: terraform destroy -auto-approve

  destroy-azure:
    name: Destroy en Azure
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./AZ
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Instalar Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Login en Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Init Terraform
        run: terraform init

      - name: Destroy recursos en Azure
        run: terraform destroy -auto-approve
